# Generated by Django 2.0.6 on 2019-05-08 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('calidad', models.IntegerField(blank=True, choices=[(0, 'mala'), (1, 'buena'), (2, 'sin calificar')], null=True)),
                ('hora', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23)], null=True)),
                ('minuto', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59)], null=True)),
                ('aforo', models.IntegerField(blank=True, null=True)),
                ('x_lamina', models.FloatField(blank=True, null=True)),
                ('y_lamina', models.FloatField(blank=True, null=True)),
                ('tipo_salida', models.CharField(blank=True, choices=[('redrio-rio', 'Redrio-Río'), ('redrio-quebradas', 'Redrio-Queb'), ('redrio-modelacion', 'Redrío-Model'), ('siata-aforo', 'Siata Aforo'), ('siata-batimetria', 'Siata-topo'), ('siata-completo', 'Siata-Completo')], max_length=30, null=True)),
                ('tramo', models.IntegerField(blank=True, null=True)),
                ('codigo_sensor_nivel', models.IntegerField(blank=True, null=True)),
                ('codigo_sensor_vel_sup', models.IntegerField(blank=True, null=True)),
                ('tipo_aforo', models.CharField(blank=True, choices=[('vadeo', 'Vadeo'), ('suspencion', 'Suspención'), ('curva calibracion', 'Curva de calibración'), ('diferencia', 'Diferencia')], max_length=50, null=True)),
                ('caudal_total', models.FloatField(blank=True, null=True)),
                ('error_caudal', models.FloatField(blank=True, null=True)),
                ('area_mojada', models.FloatField(blank=True, null=True)),
                ('profundidad_media', models.FloatField(blank=True, null=True)),
                ('perimetro_mojado', models.FloatField(blank=True, null=True)),
                ('dispositivo', models.CharField(blank=True, default='MF-PRO', max_length=15, null=True)),
                ('error_dispositivo', models.FloatField(blank=True, null=True)),
                ('ancho_superficial', models.FloatField(blank=True, null=True)),
                ('velocidad_promedio', models.FloatField(blank=True, null=True)),
                ('radio_hidraulico', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('texto_1', models.TextField(blank=True, null=True)),
                ('texto_2', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('offset', models.FloatField(blank=True, null=True)),
                ('item_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta.Basin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertical', models.IntegerField(blank=True, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('v01', models.FloatField(blank=True, null=True)),
                ('v02', models.FloatField(blank=True, null=True)),
                ('v03', models.FloatField(blank=True, null=True)),
                ('v04', models.FloatField(blank=True, null=True)),
                ('v05', models.FloatField(blank=True, null=True)),
                ('v06', models.FloatField(blank=True, null=True)),
                ('v07', models.FloatField(blank=True, null=True)),
                ('v08', models.FloatField(blank=True, null=True)),
                ('v09', models.FloatField(blank=True, null=True)),
                ('vsup', models.FloatField(blank=True, null=True)),
                ('vm', models.FloatField(blank=True, null=True)),
                ('area_i', models.FloatField(blank=True, null=True)),
                ('caudal_i', models.FloatField(blank=True, null=True)),
                ('perimetro_i', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hidraulics.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Topo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertical', models.IntegerField(blank=True, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hidraulics.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-timestamp'],
            },
        ),
    ]
