# Generated by Django 2.0.6 on 2019-05-08 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hidraulics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta.Stations'),
        ),
    ]
