# Generated by Django 2.0.6 on 2019-04-08 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('direccion', models.CharField(blank=True, max_length=120, null=True)),
                ('tipo_sensor', models.IntegerField(blank=True, choices=[(0, 'Ultrasonido'), (1, 'Radar')], null=True)),
                ('vel_sup', models.IntegerField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, max_length=120, null=True)),
                ('subcuenca', models.CharField(blank=True, max_length=120, null=True)),
                ('barrio', models.CharField(blank=True, max_length=120, null=True)),
                ('source', models.CharField(blank=True, max_length=120, null=True)),
                ('l_cuenca', models.FloatField(blank=True, max_length=120, null=True)),
                ('longitud_basin', models.FloatField(blank=True, max_length=120, null=True)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('h_cauce_max', models.FloatField(blank=True, max_length=120, null=True)),
                ('pend_cuenca', models.FloatField(blank=True, max_length=120, null=True)),
                ('hmax', models.FloatField(blank=True, max_length=120, null=True)),
                ('kml_path', models.CharField(blank=True, max_length=120, null=True)),
                ('l_cauce', models.FloatField(blank=True, max_length=120, null=True)),
                ('perimetro', models.FloatField(blank=True, max_length=120, null=True)),
                ('municipio', models.CharField(blank=True, max_length=120, null=True)),
                ('hmean', models.CharField(blank=True, max_length=120, null=True)),
                ('flag_modelo_estadistico', models.IntegerField(blank=True, choices=[(1, 'si'), (0, 'no')], null=True)),
                ('dpx', models.FloatField(blank=True, max_length=120, null=True)),
                ('camara_path', models.CharField(blank=True, max_length=120, null=True)),
                ('rain_path', models.CharField(blank=True, max_length=120, null=True)),
                ('pic_path', models.CharField(blank=True, max_length=120, null=True)),
                ('latitud', models.FloatField(blank=True, max_length=120, null=True)),
                ('polygon_path', models.CharField(blank=True, max_length=120, null=True)),
                ('centro_x', models.FloatField(blank=True, max_length=120, null=True)),
                ('centro_y', models.FloatField(blank=True, max_length=120, null=True)),
                ('pluvios', models.CharField(blank=True, max_length=120, null=True)),
                ('red', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono_contacto', models.BigIntegerField(blank=True, null=True)),
                ('offset_old', models.FloatField(blank=True, max_length=120, null=True)),
                ('flag_modelo_wmf', models.IntegerField(blank=True, choices=[(1, 'si'), (0, 'no')], null=True)),
                ('net_path', models.CharField(blank=True, max_length=120, null=True)),
                ('x_sensor', models.FloatField(blank=True, max_length=120, null=True)),
                ('latitud_basin', models.FloatField(blank=True, max_length=120, null=True)),
                ('sirena', models.CharField(blank=True, choices=[(1, 'si'), (0, 'no')], max_length=120, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activa'), ('P', 'Pendiente'), ('I', 'Inactiva')], max_length=1, null=True)),
                ('clase', models.CharField(blank=True, max_length=120, null=True)),
                ('longitud', models.FloatField(blank=True, max_length=120, null=True)),
                ('slug', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('nombre_contacto', models.CharField(blank=True, max_length=120, null=True)),
                ('hmin', models.FloatField(blank=True, max_length=120, null=True)),
                ('pend_cauce', models.FloatField(blank=True, max_length=120, null=True)),
                ('nc_path', models.CharField(blank=True, max_length=120, null=True)),
                ('stream_path', models.CharField(blank=True, max_length=120, null=True)),
                ('n1', models.FloatField(blank=True, max_length=120, null=True)),
                ('n2', models.FloatField(blank=True, max_length=120, null=True)),
                ('n3', models.FloatField(blank=True, max_length=120, null=True)),
                ('n4', models.FloatField(blank=True, max_length=120, null=True)),
                ('l_tot_cauces', models.FloatField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
